# build environment
FROM node:13.12.0-alpine as build_react_app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ./sscpatfront/package.json ./
COPY ./sscpatfront/package-lock.json ./

RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY ./sscpatfront ./
COPY ./sscpatfront/src/utils/global.prod.local.js ./src/utils/global.js
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build_react_app /app/build /usr/share/nginx/html
COPY ./sscpatfront/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]