# Generated by Django 2.2.10 on 2021-05-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='title_academic_project',
            field=models.TextField(max_length=1024, unique=True, verbose_name='title of academic project'),
        ),
    ]
