# Generated by Django 2.2.10 on 2021-05-05 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0002_auto_20210503_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='description_project',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Description project'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='external_tutors',
            field=models.ManyToManyField(related_name='etutor_projects', to='sscpat.ExternalTutor'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sscpat.Student', verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='tutors',
            field=models.ManyToManyField(related_name='tutor_projects', to='sscpat.Tutor'),
        ),
    ]
