# Generated by Django 2.2.10 on 2021-09-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0003_inscription_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('date_init', models.DateField(verbose_name='date initial')),
                ('date_end', models.DateField(verbose_name='date finalization')),
                ('date_init_old', models.DateField(verbose_name='date initial')),
                ('date_end_old', models.DateField(verbose_name='date finalization')),
                ('note', models.CharField(max_length=255, verbose_name='note')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('format', models.CharField(max_length=32, verbose_name='format')),
                ('path', models.FileField(upload_to='tracing_progress_file/', verbose_name='file path')),
                ('img_medium', models.FileField(default=None, max_length=255, null=True, upload_to='tracing_progress_file/image_medium', verbose_name='Image Medium')),
                ('thumbnail', models.FileField(default=None, max_length=255, null=True, upload_to='tracing_progress_file/thumbnail', verbose_name='Image Small')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datelogs', to='sscpat.Inscription')),
            ],
            options={
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
