# Generated by Django 2.2.10 on 2021-05-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0003_auto_20210505_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracingstudent',
            name='number',
            field=models.IntegerField(default=1, verbose_name='progress number'),
        ),
    ]
