# Generated by Django 2.2.10 on 2021-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0004_tracingstudent_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracingstudent',
            name='reviewed_date_admin',
        ),
        migrations.RemoveField(
            model_name='tracingstudent',
            name='reviewed_date_tutor',
        ),
        migrations.AddField(
            model_name='tracingstudent',
            name='institution_report_was_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracingstudent',
            name='require_admin_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracingstudent',
            name='require_external_tutor_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracingstudent',
            name='require_institution_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracingstudent',
            name='require_tutor_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracingstudent',
            name='reviewed_by_external_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
