# Generated by Django 2.2.10 on 2021-09-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0004_datelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datelog',
            name='date_end_old',
            field=models.DateField(verbose_name='date finalization old'),
        ),
        migrations.AlterField(
            model_name='datelog',
            name='date_init_old',
            field=models.DateField(verbose_name='date initial old'),
        ),
        migrations.AlterField(
            model_name='datelog',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='note'),
        ),
    ]
