# Generated by Django 2.2.10 on 2021-05-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0005_auto_20210506_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracingstudent',
            name='is_final_document',
            field=models.BooleanField(default=False, verbose_name='is final document'),
        ),
        migrations.AlterField(
            model_name='tracingstudentfile',
            name='tracingstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sscpat.TracingStudent', verbose_name='inscriptions'),
        ),
    ]
