# Generated by Django 2.2.10 on 2021-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0005_auto_20210902_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalityconfig',
            name='has_evaluating_court',
            field=models.BooleanField(default=True, verbose_name='has evaluating court'),
        ),
        migrations.AddField(
            model_name='modalityconfig',
            name='has_review_commission',
            field=models.BooleanField(default=True, verbose_name='has review commission '),
        ),
    ]
