# Generated by Django 2.2.10 on 2021-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0006_auto_20210507_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracingprogress',
            old_name='tutor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tracingprogress',
            name='comment',
        ),
        migrations.AddField(
            model_name='tracingprogress',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tracingprogress',
            name='typetracing',
            field=models.CharField(choices=[('INTERNAL_TUTOR', 'Tutor'), ('EXTERNAL_TUTOR', 'External tutor'), ('INSTITUTION_REPORT', 'institution report'), ('COMMENT', 'Comment')], default=None, max_length=20, null=True, verbose_name='type'),
        ),
    ]
