# Generated by Django 2.2.10 on 2021-09-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0006_auto_20210922_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='tutors_evaluating_court',
            field=models.ManyToManyField(related_name='projects_court', to='sscpat.Tutor'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='tutors_review_commission',
            field=models.ManyToManyField(related_name='projects_review', to='sscpat.Tutor'),
        ),
    ]
