# Generated by Django 2.2.10 on 2021-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0007_auto_20210512_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracingprogress',
            name='typetracing',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INTERNAL_TUTOR', 'Tutor'), ('EXTERNAL_TUTOR', 'External tutor'), ('INSTITUTION_REPORT', 'institution report'), ('COMMENT', 'Comment')], default='COMMENT', max_length=20, null=True, verbose_name='type'),
        ),
    ]
