# Generated by Django 2.2.10 on 2022-01-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0007_auto_20210923_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='document_student',
            field=models.ManyToManyField(related_name='modalities_document_student', to='sscpat.Document'),
        ),
    ]
