# Generated by Django 2.2.10 on 2021-05-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0008_auto_20210512_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracingstudentfile',
            name='img_medium',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='tracing_student_file/image_medium', verbose_name='Image Medium'),
        ),
        migrations.AddField(
            model_name='tracingstudentfile',
            name='thumbnail',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='tracing_student_file/thumbnail', verbose_name='Image Small'),
        ),
    ]
