# Generated by Django 2.2.10 on 2021-05-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0009_auto_20210512_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracingstudentfile',
            name='path',
            field=models.FileField(upload_to='tracing_student_file/images/', verbose_name='file path'),
        ),
    ]
