# Generated by Django 2.2.10 on 2021-05-13 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0010_auto_20210513_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracingprogressfile',
            name='tracingprgress',
        ),
        migrations.AddField(
            model_name='tracingprogressfile',
            name='img_medium',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='tracing_progress_file/image_medium', verbose_name='Image Medium'),
        ),
        migrations.AddField(
            model_name='tracingprogressfile',
            name='thumbnail',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='tracing_progress_file/thumbnail', verbose_name='Image Small'),
        ),
        migrations.AddField(
            model_name='tracingprogressfile',
            name='tracingprogress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sscpat.TracingProgress', verbose_name='tracingstundent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracingprogressfile',
            name='path',
            field=models.FileField(upload_to='tracing_progress_file/images/', verbose_name='file path'),
        ),
    ]
