# Generated by Django 2.2.10 on 2021-05-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0011_auto_20210513_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracingprogress',
            name='tracingstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracingprogress', to='sscpat.TracingStudent', verbose_name='tracingstudent'),
        ),
        migrations.AlterField(
            model_name='tracingstudent',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracingstundents', to='sscpat.Inscription', verbose_name='inscription'),
        ),
    ]
