# Generated by Django 2.2.10 on 2021-05-19 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0012_auto_20210517_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='has_time_extension',
            field=models.BooleanField(default=False, verbose_name='Has extention time'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='month_duration',
            field=models.PositiveIntegerField(default=6, verbose_name='month_duration'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='month_extension',
            field=models.PositiveIntegerField(default=0, verbose_name='month extension'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='month_max_duration',
            field=models.PositiveIntegerField(default=6, verbose_name='month_doration'),
        ),
        migrations.AlterField(
            model_name='tracingstudent',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracingstudents', to='sscpat.Inscription', verbose_name='inscription'),
        ),
    ]
