# Generated by Django 2.2.10 on 2021-06-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0013_auto_20210519_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time_send',
            field=models.IntegerField(default=-2, verbose_name='time_send'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='academic_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sscpat.AcademicPeriod'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sscpat.Institution'),
        ),
    ]
