# Generated by Django 2.2.10 on 2021-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0014_auto_20210608_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
