# Generated by Django 2.2.10 on 2021-06-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0015_auto_20210608_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normative',
            name='file',
        ),
        migrations.AddField(
            model_name='normative',
            name='format',
            field=models.CharField(default=None, max_length=32, verbose_name='format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normative',
            name='path',
            field=models.FileField(default='', upload_to='modality_normative/', verbose_name='file path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normative',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normatives', to='sscpat.Modality', verbose_name='modality'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='title'),
        ),
    ]
