# Generated by Django 2.2.10 on 2021-06-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0016_auto_20210608_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('format', models.CharField(max_length=32, verbose_name='format')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='size')),
                ('path', models.FileField(upload_to='tracing_student_file/images/', verbose_name='file path')),
                ('img_medium', models.FileField(default=None, max_length=255, null=True, upload_to='tracing_student_file/image_medium', verbose_name='Image Medium')),
                ('thumbnail', models.FileField(default=None, max_length=255, null=True, upload_to='tracing_student_file/thumbnail', verbose_name='Image Small')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='inscriptiondocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inscriptiondocument',
            name='reviewed_date',
        ),
        migrations.AddField(
            model_name='inscriptiondocument',
            name='deadline_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscriptiondocument',
            name='reviewer_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sscpat.Modality', verbose_name='inscriptions'),
        ),
        migrations.AlterField(
            model_name='inscriptiondocument',
            name='file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sscpat.File', verbose_name='file'),
        ),
    ]
