# Generated by Django 2.2.10 on 2021-06-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0018_auto_20210609_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionInitialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('deadline_date', models.DateField(default=None, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_date', models.DateField(default=None, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sscpat.Document', verbose_name='documents')),
                ('file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sscpat.File', verbose_name='file')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sscpat.Inscription', verbose_name='inscriptions')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
