# Generated by Django 2.2.10 on 2021-06-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0019_inscriptioninitialdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptiondocument',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sscpat.Inscription', verbose_name='inscriptions'),
        ),
    ]
