# Generated by Django 2.2.10 on 2021-06-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscpat', '0020_auto_20210609_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='useraction',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='was_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='format',
            field=models.CharField(choices=[('0', 'No thing'), ('1', 'Account created'), ('2', 'Account add'), ('3', 'Welcome'), ('4', 'Project assigned'), ('6', 'progress uploaded'), ('7', 'review progress uploaded'), ('8', 'Institution report uploaded')], default='0', max_length=2, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='notification',
            name='inscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sscpat.Inscription', verbose_name='inscription'),
        ),
        migrations.AddField(
            model_name='notification',
            name='inscription_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sscpat.InscriptionDocument', verbose_name='inscription_document'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='tracing_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sscpat.TracingProgress', verbose_name='tracing_progress'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tracing_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sscpat.TracingStudent', verbose_name='tracing_student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Accionador'),
        ),
        migrations.AlterField(
            model_name='inscriptioninitialdocument',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialdocuments', to='sscpat.Inscription', verbose_name='inscriptions'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
