// not found
export const NOT_FOUND = "NOT_FOUND";

// Messages
export const GET_ERRORS = "GET_ERRORS";
export const MESSAGE_INFO = "MESSAGE_INFO";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_ALERT = "MESSAGE_ALERT";
export const MESSAGE_DANGER = "MESSAGE_DANGER";
export const MESSAGE_DEFAULT = "MESSAGE_DEFAULT";

export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Type USER
export const ADMIN = "ADMIN";
export const TUTOR = "TUTOR";
export const EXTERNAL_TUTOR = "EXTERNAL_TUTOR";
export const STUDENT = "STUDENT";

// STATUS PROYECT
export const UNDER_DEVELOPMENT = "UNDER_DEVELOPMENT";
export const CONCLUDED_SUCCESSFULLY = "CONCLUDED_SUCCESSFULLY";
export const ABANDONED = "ABANDONED";

export const TUTOR_ADDED = "TUTOR_ADDED";
export const TUTOR_REMOVED = "TUTOR_REMOVED";
export const TUTOR_ALREADY_ADDED = "TUTOR_ALREADY_ADDED";
export const TUTOR_SEARCH = "TUTOR_SEARCH";
export const GET_TUTORS = "GET_TUTORS";
export const GET_TUTOR = "GET_TUTOR";
export const MINIMAL_LIST_TUTOR = "MINIMAL_LIST_TUTOR";

export const ADD_EXTERNAL_TUTOR = "ADD_EXTERNAL_TUTOR";
export const LIST_EXTERNAL_TUTOR = "LIST_EXTERNAL_TUTOR";
export const GET_EXTERNAL_TUTOR = "GET_EXTERNAL_TUTOR";
export const UPDATE_EXTERNAL_TUTOR = "UPDATE_EXTERNAL_TUTOR";
export const DELETE_EXTERNAL_TUTOR = "DELETE_EXTERNAL_TUTOR";
export const MINIMAL_LIST_EXTERNAL_TUTOR = "MINIMAL_LIST_EXTERNAL_TUTOR";

export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENT = "GET_STUDENT";

export const FORM_LOADING = "FORM_LOADING";
export const FORM_NOT_LOADING = "FORM_NOT_LOADING";
export const FORM_FAILED = "FORM_FAILED";
export const FORM_SUCCESS = "FORM_SUCCESS";

export const DELETE_USER = "DELETE_USER";
export const GET_USERS = "GET_USERS";


// ACADEMIC PERIOD

export const DELETE_ACADEMIC_PERIOD = "DELETE_ACADEMIC_PERIOD";
export const LIST_ACADEMIC_PERIOD = "LIST_ACADEMIC_PERIOD";
export const ADD_ACADEMIC_PERIOD = "ADD_ACADEMIC_PERIOD";
export const UPDATE_ACADEMIC_PERIOD = "UPDATE_ACADEMIC_PERIOD";
export const GET_ACADEMIC_PERIOD = "GET_ACADEMIC_PERIOD";

// DOCUMENTS

export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const LIST_DOCUMENT = "LIST_DOCUMENT";
export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const GET_DOCUMENT = "GET_DOCUMENT";

// INSTITUTIONS

export const DELETE_INSTITUTION = "DELETE_INSTITUTION";
export const LIST_INSTITUTION = "LIST_INSTITUTION";
export const ADD_INSTITUTION = "ADD_INSTITUTION";
export const UPDATE_INSTITUTION = "UPDATE_INSTITUTION";
export const GET_INSTITUTION = "GET_INSTITUTION";

// MODALITY

export const DELETE_MODALITY = "DELETE_MODALITY";
export const LIST_MODALITY = "LIST_MODALITY";
export const ADD_MODALITY = "ADD_MODALITY";
export const UPDATE_MODALITY = "UPDATE_MODALITY";
export const GET_MODALITY = "GET_MODALITY";

// PROJECTS
export const ADD_PROJECT = "ADD_PROJECT";
export const LIST_PROJECT = "LIST_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const MINIMAL_LIST_PROJECT = "MINIMAL_LIST_PROJECT";
export const GET_DOCUMENT_PROJECT = "GET_DOCUMENT_PROJECT";
export const UPDATE_DOCUMENT_LIST = "UPDATE_DOCUMENT_LIST";
export const UPDATE_DOCUMENT_INSCRIPTION_LIST = "UPDATE_DOCUMENT_INSCRIPTION_LIST";
export const DATE_MONTHS= "DATE_MONTHS";

// TRACING PROJECT BY STUDENT
export const DELETE_TRACINGSTUDENT = "DELETE_TRACINGSTUDENT";
export const LIST_TRACINGSTUDENT = "LIST_TRACINGSTUDENT";
export const LIST_TRACINGSTUDENT_REPORT ="LIST_TRACINGSTUDENT_REPORT";

export const ADD_TRACINGSTUDENT = "ADD_TRACINGSTUDENT";
export const UPDATE_TRACINGSTUDENT = "UPDATE_TRACINGSTUDENT";
export const GET_TRACINGSTUDENT = "GET_TRACINGSTUDENT";


// TRACING PROGRESS 

export const DELETE_TRACINGPROGRESS = "DELETE_TRACINGPROGRESS"
export const LIST_TRACINGPROGRESS = "LIST_TRACINGPROGRESS"
export const LIST_TRACINGPROGRESS_REPORT = "LIST_TRACINGPROGRESS_REPORT" ;
export const ADD_TRACINGPROGRESS = "ADD_TRACINGPROGRESS"
export const UPDATE_TRACINGPROGRESS = "UPDATE_TRACINGPROGRESS"
export const GET_TRACINGPROGRESS = "GET_TRACINGPROGRESS"

// REPORTS 
export const GET_TUTORS_REPORT = "GET_TUTORS_REPORT"


// ACCEPTED FILE TYPES
export const ACCEPTED_FILES = [
  "application/pdf", // PDF
  "image/jpeg",
  "image/jpx",
  "image/png",
  "image/gif",
  "image/webp",
  "image/x-canon-cr2",
  "image/tiff",
  "image/bmp",
  "image/vnd.ms-photo",
  "image/vnd.adobe.photoshop",
  "image/x-icon",
  "image/heic",
];


// info
export const GET_INFO="GET_INFO"


// NOTIFICATIONS

export const LIST_NOTIFICATIONS = "LIST_NOTIFICATIONS"
export const LIST_ADD_NOTIFICATIONS = "LIST_ADD_NOTIFICATIONS"
export const NUMBER_NOTIFICATIONS = "NUMBER_NOTIFICATION"
export const SET_ZERO = "SET_ZERO"


