"""Filetype choices"""

#TYPE_CHOICES=[ ("key","value").(,)..]

IMAGETYPE_CHOICES=[
    ("jpg","image/jpeg",),
    ("jpx","image/jpx",),
    ("png","image/png",),
    ("gif","image/gif",),
    ("webp","image/webp",),
    ("cr2","image/x-canon-cr2",),
    ("tif","image/tiff",),
    ("bmp","image/bmp",),
    ("jxr","image/vnd.ms-photo",),
    ("psd","image/vnd.adobe.photoshop",),
    ("ico","image/x-icon",),
    ("heic","image/heic",),
]


VIDEOTYPE_CHOICES=[
    ("mp4","video/mp4"),
    ("m4v","video/x-m4v"),
    ("mkv","video/x-matroska"),
    ("webm","video/webm"),
    ("mov","video/quicktime"),
    ("avi","video/x-msvideo"),
    ("wmv","video/x-ms-wmv"),
    ("mpg","video/mpeg"),
    ("flv","video/x-flv"),
]

AUDIOTYPE_CHOICES=[
    ("mid","audio/midi"),
    ("mp3","audio/mpeg"),
    ("m4a","audio/m4a"),
    ("ogg","audio/ogg"),
    ("flac","audio/x-flac"),
    ("wav","audio/x-wav"),
    ("amr","audio/amr"),
]
ARCHIVETYPE_CHOICES=[
    ("epub","application/epub+zip"),
    ("zip","application/zip"),
    ("tar","application/x-tar"),
    ("rar","application/x-rar-compressed"),
    ("gz","application/gzip"),
    ("bz2","application/x-bzip2"),
    ("7z","application/x-7z-compressed"),
    ("xz","application/x-xz"),
    ("pdf","application/pdf"),
    ("exe","application/x-msdownload"),
    ("swf","application/x-shockwave-flash"),
    ("rtf","application/rtf"),
    ("eot","application/octet-stream"),
    ("ps","application/postscript"),
    ("sqlite","application/x-sqlite3"),
    ("nes","application/x-nintendo-nes-rom"),
    ("crx","application/x-google-chrome-extension"),
    ("cab","application/vnd.ms-cab-compressed"),
    ("deb","application/x-deb"),
    ("ar","application/x-unix-archive"),
    ("Z","application/x-compress"),
    ("lz","application/x-lzip"),
]
FONTTYPE_CHOICES=[
    ("woff","application/font-woff"),
    ("woff2","application/font-woff"),
    ("ttf","application/font-sfnt"),
    ("otf","application/font-sfnt"),
]


IMAGEMIME_CHOICES=[
"image/jpeg",
"image/jpx",
"image/png",
"image/gif",
"image/webp",
"image/x-canon-cr2",
"image/tiff",
"image/bmp",
"image/vnd.ms-photo",
"image/vnd.adobe.photoshop",
"image/x-icon",
"image/heic",
]


VIDEOMIME_CHOICES=[
"video/mp4",
"video/x-m4v",
"video/x-matroska",
"video/webm",
"video/quicktime",
"video/x-msvideo",
"video/x-ms-wmv",
"video/mpeg",
"video/x-flv",
]

AUDIOMIME_CHOICES=[
"audio/midi",
"audio/mpeg",
"audio/m4a",
"audio/ogg",
"audio/x-flac",
"audio/x-wav",
"audio/amr",
]
ARCHIVEMIME_CHOICES=[
"application/epub+zip",
"application/zip",
"application/x-tar",
"application/x-rar-compressed",
"application/gzip",
"application/x-bzip2",
"application/x-7z-compressed",
"application/x-xz",
"application/pdf",
"application/x-msdownload",
"application/x-shockwave-flash",
"application/rtf",
"application/octet-stream",
"application/postscript",
"application/x-sqlite3",
"application/x-nintendo-nes-rom",
"application/x-google-chrome-extension",
"application/vnd.ms-cab-compressed",
"application/x-deb",
"application/x-unix-archive",
"application/x-compress",
"application/x-lzip",
]
FONTMIME_CHOICES=[
"application/font-woff",
"application/font-woff",
"application/font-sfnt",
"application/font-sfnt",
]